In [118]:
#Практика работы с numpy


In [ ]:
import numpy as np

In [39]:
b = np.array(list(range(20)))
dir(b)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [44]:
a = np.array([10, 20, 40], int)
b = np.array([-1, 0, 2], int)
np.dot(a,b)

70

In [47]:
a = np.array([[5, 1, -2, 0],[0, 3, 4, 3],[2, 3, 1, 1]])
b = np.array([[1, -3], [2, -2], [3, -1], [0,0]])
print((a@b).sum())


-8


In [83]:
#Перемножение матриц
#Напишите две функции, каждая из которых перемножает две квадратные матрицы: одна без использования встроенных функций numpy, а другая --- с помощью numpy.
import numpy as np

def no_numpy_mult(first, second):
    """
    param first: list of "size" lists, each contains "size" floats
    param first: list of "size" lists, each contains "size" floats
    """
    result = []
    for t in range(len(first)):
        a = []
        for i in range(len(second[0])):
            b = [second[j][i] for j in range(len(second))]
            a.append(sum([l*m for l, m in zip(first[t], b)]))
            #print(a)
        result.append(a)
    return result

def numpy_mult(first, second):
    """
    param first: np.array[size, size]
    param second: np.array[size, size]
    """
    result = first@second
    return result

print(no_numpy_mult(list([[5, 1, -2, 0],[0, 3, 4, 3],[2, 3, 1, 1]]), list([[1, -3], [2, -2], [3, -1], [0,0]])))
print('\n')
print(numpy_mult(np.array([[5, 1, -2, 0],[0, 3, 4, 3],[2, 3, 1, 1]]), np.array([[1, -3], [2, -2], [3, -1], [0,0]])))

[[1, -15], [18, -10], [11, -13]]


[[  1 -15]
 [ 18 -10]
 [ 11 -13]]


In [84]:
#Вам подаются на вход два вектора a и b в трехмерном пространстве. 
#Реализуйте их скалярное произведение с помощью numpy и без. 

import numpy as np

def no_numpy_scalar(v1, v2):
    #param v1, v2: lists of 3 ints
    result = sum([x*y for x, y in zip(v1,v2)])
    return result

def numpy_scalar (v1, v2):
    #param v1, v2: np.arrays[3]
    result = np.dot(v1,v2)
    return result

print(no_numpy_scalar([1, -15, 2], [18, -10, 7]))
print('\n')
print(numpy_scalar([1, -15, 2], [18, -10, 7]))

182


182


In [110]:
#Напишите функцию, которая находит сумму четных элементов на главной диагонали квадратной матрицы (именно чётных элементов, а не элементов на чётных позициях!)
#Если чётных элементов нет, то вывести 0. Используйте библиотеку numpy.

import numpy as np #не стирать!        

def diag_2k(a):
    result = sum(filter(lambda x : x % 2 == 0, np.diag(a)))
    #result = np.diag(a)[np.diag(a)%2==0].sum()
    #тоже работает
    return result

print(diag_2k(np.array([[2, 1, -2, 0],[0, 2, 4, 3],[2, 3, -2, 1], [2, 3, 2, 0]])))

2


In [116]:
#

import numpy as np

def cumsum(A):
    #param A: np.array[m,n]
    result = np.cumsum(A, axis=1)
    return result

print(cumsum(np.array([[2, 1, -2, 0],[0, 2, 4, 3],[2, 3, -2, 1], [2, 3, 2, 0]])))

[[2 3 1 1]
 [0 2 6 9]
 [2 5 3 4]
 [2 5 7 7]]


In [161]:
import numpy as np
def change(i, a):
    i[1::2] = a
    i[0::2] **= 3
    return i[::-1]

def transform(X, a=1):
    y = X.copy()
    result = np.array([change(i, a) for i in y])
    return np.array(([np.hstack((X[i], result[i])) for i in range(len(X))]))

transform(np.array([[100,200,300,400,500]]), 0)

array([[      100,       200,       300,       400,       500, 125000000,
                0,  27000000,         0,   1000000]])

In [162]:
import numpy as np

def encode(a):
    occur = []
    result = []
    i = 0
    while i < len(a):
        cnt = 0
        j = i
        while j < len(a) and a[j] == a[i]:
            j += 1
            cnt +=1
        result.append(a[i])
        i = j
        occur.append(cnt)
    return (np.array(result), np.array(occur))

encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3]))

(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))